name: my-env
channels:
  - defaults
dependencies:
  - python= 3.10.11
  - pip
  - pip:
      - scikit-learn
      - joblib
      - numpy
      - pandas
      - azure-ai-ml
      - azureml-defaults
      - inference-schema
      - azureml-mlflow



